// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=browserifytest2;AccountKey=null;EndpointSuffix=core.windows.net';
  process.env['AZURE_STORAGE_CONNECTION_STRING_PREMIUM_ACCOUNT'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonliprepp;AccountKey=null;EndpointSuffix=rr1xio.xstore-test.windows-int.net';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbe9-001c-0007-15ab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbe9-001c-0007-15ab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  etag: '"0x8D4CDC29571305A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5f3e5458-001c-000d-66ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:38 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  etag: '"0x8D4CDC29571305A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5f3e5458-001c-000d-66ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:38 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  etag: '"0x8D4CDC295E26D63"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'd0130a43-001c-0000-69ab-ff1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:38 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  etag: '"0x8D4CDC295E26D63"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'd0130a43-001c-0000-69ab-ff1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:38 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC295E26D63"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-access-tier-inferred': 'true',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'fe9fbb11-001c-0011-33ab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC295E26D63"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-access-tier-inferred': 'true',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'fe9fbb11-001c-0011-33ab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  etag: '"0x8D4CDC29571305A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'b511f769-001c-000c-5eab-ffc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:38 GMT',
  etag: '"0x8D4CDC29571305A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'b511f769-001c-000c-5eab-ffc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4646bf9b-001c-0004-61ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:42 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4646bf9b-001c-0004-61ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:42 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6a6c26c-001c-0006-48ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6a6c26c-001c-0006-48ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:45 GMT',
  etag: '"0x8D4CDC299FBC00B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2266a06f-001c-0005-7eab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:45 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:45 GMT',
  etag: '"0x8D4CDC299FBC00B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2266a06f-001c-0005-7eab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:45 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  etag: '"0x8D4CDC29A57B04A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '9193515f-001c-0014-6cab-ff7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:45 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  etag: '"0x8D4CDC29A57B04A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '9193515f-001c-0014-6cab-ff7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:45 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '81ad73cc-001c-0003-08ab-ff2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:47 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '81ad73cc-001c-0003-08ab-ff2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:47 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC29A57B04A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P4',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '31edce17-001c-0002-43ab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC29A57B04A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P4',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '31edce17-001c-0002-43ab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<EnumerationResults ServiceEndpoint=\"https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Tue, 18 Jul 2017 09:51:46 GMT</Last-Modified><Etag>0x8D4CDC29A57B04A</Etag><Content-Length>0</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding/><Content-Language/><Content-MD5/><Cache-Control/><Content-Disposition/><x-ms-blob-sequence-number>0</x-ms-blob-sequence-number><BlobType>PageBlob</BlobType><AccessTier>P4</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker/></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '525bae98-001c-0013-14ab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<EnumerationResults ServiceEndpoint=\"https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Tue, 18 Jul 2017 09:51:46 GMT</Last-Modified><Etag>0x8D4CDC29A57B04A</Etag><Content-Length>0</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding/><Content-Language/><Content-MD5/><Cache-Control/><Content-Disposition/><x-ms-blob-sequence-number>0</x-ms-blob-sequence-number><BlobType>PageBlob</BlobType><AccessTier>P4</AccessTier><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>false</ServerEncrypted></Properties></Blob></Blobs><NextMarker/></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '525bae98-001c-0013-14ab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb2bfce5-001c-000b-17ab-ff4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:50 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb2bfce5-001c-000b-17ab-ff4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:50 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC29A57B04A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '4c65013d-001c-0001-31ab-fff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC29A57B04A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '4c65013d-001c-0001-31ab-fff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>CannotChangeToLowerTier</Code><Message>A higher blob tier has already been explicitly set.\nRequestId:95629edd-001c-0009-2bab-ff9092000000\nTime:2017-07-18T09:51:53.3447055Z</Message></Error>", { 'content-length': '244',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '95629edd-001c-0009-2bab-ff9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>CannotChangeToLowerTier</Code><Message>A higher blob tier has already been explicitly set.\nRequestId:95629edd-001c-0009-2bab-ff9092000000\nTime:2017-07-18T09:51:53.3447055Z</Message></Error>", { 'content-length': '244',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '95629edd-001c-0009-2bab-ff9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC29A57B04A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '613c6d3b-001c-000f-2bab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:46 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC29A57B04A"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P6',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '613c6d3b-001c-000f-2bab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:45 GMT',
  etag: '"0x8D4CDC299FBC00B"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '51b9db93-001c-0008-76ab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:45 GMT',
  etag: '"0x8D4CDC299FBC00B"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '51b9db93-001c-0008-76ab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5f3e545c-001c-000d-69ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:56 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5f3e545c-001c-000d-69ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:56 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:50:49 GMT',
  etag: '"0x8D4CDC2789385E2"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'fe9fbb1d-001c-0011-37ab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:50:49 GMT',
  etag: '"0x8D4CDC2789385E2"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'fe9fbb1d-001c-0011-37ab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:57 GMT',
  etag: '"0x8D4CDC2A13B0DAB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '4646bfa2-001c-0004-68ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:57 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:57 GMT',
  etag: '"0x8D4CDC2A13B0DAB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '4646bfa2-001c-0004-68ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:57 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:59 GMT',
  etag: '"0x8D4CDC2A22EABCD"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e6a6c275-001c-0006-50ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:59 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:51:59 GMT',
  etag: '"0x8D4CDC2A22EABCD"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e6a6c275-001c-0006-50ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:51:59 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:59 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2A22EABCD"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '2266a550-001c-0005-5cab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5temp')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:51:59 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2A22EABCD"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '2266a550-001c-0005-5cab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:50:49 GMT',
  etag: '"0x8D4CDC2789385E2"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '81ad78fd-001c-0003-37ab-ff2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:50:49 GMT',
  etag: '"0x8D4CDC2789385E2"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '81ad78fd-001c-0003-37ab-ff2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '31edce27-001c-0002-4cab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:01 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '31edce27-001c-0002-4cab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:01 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb2c010f-001c-000b-40ab-ff4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb2c010f-001c-000b-40ab-ff4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:04 GMT',
  etag: '"0x8D4CDC2A52CC0A5"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4c650140-001c-0001-33ab-fff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:03 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:04 GMT',
  etag: '"0x8D4CDC2A52CC0A5"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4c650140-001c-0001-33ab-fff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:03 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:05 GMT',
  etag: '"0x8D4CDC2A59FAA88"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '57130ec0-001c-000a-6bab-ffa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:04 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:05 GMT',
  etag: '"0x8D4CDC2A59FAA88"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '57130ec0-001c-000a-6bab-ffa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:04 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7temp')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTierInadequateForContentLength</Code><Message>Specified blob tier size limit cannot be less than content length.\nRequestId:9562a30a-001c-0009-58ab-ff9092000000\nTime:2017-07-18T09:52:06.5418627Z</Message></Error>", { 'content-length': '270',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9562a30a-001c-0009-58ab-ff9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7temp')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>BlobTierInadequateForContentLength</Code><Message>Specified blob tier size limit cannot be less than content length.\nRequestId:9562a30a-001c-0009-58ab-ff9092000000\nTime:2017-07-18T09:52:06.5418627Z</Message></Error>", { 'content-length': '270',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9562a30a-001c-0009-58ab-ff9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:04 GMT',
  etag: '"0x8D4CDC2A52CC0A5"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '613c6d49-001c-000f-30ab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:04 GMT',
  etag: '"0x8D4CDC2A52CC0A5"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '613c6d49-001c-000f-30ab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51b9db99-001c-0008-7bab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:08 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51b9db99-001c-0008-7bab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:08 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbf1-001c-0007-1aab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:09 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbf1-001c-0007-1aab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:09 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:10 GMT',
  etag: '"0x8D4CDC2A8BF6500"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '525baea0-001c-0013-1aab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:10 GMT',
  etag: '"0x8D4CDC2A8BF6500"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '525baea0-001c-0013-1aab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:11 GMT',
  etag: '"0x8D4CDC2A9182534"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '5f3e5464-001c-000d-6fab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:11 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:11 GMT',
  etag: '"0x8D4CDC2A9182534"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '5f3e5464-001c-000d-6fab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:11 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9temp')
  .reply(400, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InvalidBlobTier</Code><Message>The specified blob tier is invalid.\nRequestId:fe9fbb23-001c-0011-3cab-ff28a3000000\nTime:2017-07-18T09:52:13.9677627Z</Message></Error>", { 'content-length': '220',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fe9fbb23-001c-0011-3cab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9temp')
  .reply(400, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<Error><Code>InvalidBlobTier</Code><Message>The specified blob tier is invalid.\nRequestId:fe9fbb23-001c-0011-3cab-ff28a3000000\nTime:2017-07-18T09:52:13.9677627Z</Message></Error>", { 'content-length': '220',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fe9fbb23-001c-0011-3cab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:10 GMT',
  etag: '"0x8D4CDC2A8BF6500"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '2266a97e-001c-0005-09ab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:10 GMT',
  etag: '"0x8D4CDC2A8BF6500"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '2266a97e-001c-0005-09ab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4c650144-001c-0001-36ab-fff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:15 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4c650144-001c-0001-36ab-fff87d000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:15 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbf3-001c-0007-1cab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbf3-001c-0007-1cab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:17 GMT',
  etag: '"0x8D4CDC2AD1EFF21"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4646bfb4-001c-0004-71ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:17 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:17 GMT',
  etag: '"0x8D4CDC2AD1EFF21"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4646bfb4-001c-0004-71ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:17 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:24 GMT',
  etag: '"0x8D4CDC2B0FDA352"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e6a6c27b-001c-0006-54ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:24 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:24 GMT',
  etag: '"0x8D4CDC2B0FDA352"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e6a6c27b-001c-0006-54ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:24 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:25 GMT',
  etag: '"0x8D4CDC2B194B23B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '31edce35-001c-0002-59ab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:25 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:25 GMT',
  etag: '"0x8D4CDC2B194B23B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '31edce35-001c-0002-59ab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:25 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Tue, 18 Jul 2017 09:52:28 GMT',
  etag: '"0x8D4CDC2B3B13CC7"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '525baea4-001c-0013-1eab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:28 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Tue, 18 Jul 2017 09:52:28 GMT',
  etag: '"0x8D4CDC2B3B13CC7"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '525baea4-001c-0013-1eab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:28 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=properties')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:29 GMT',
  etag: '"0x8D4CDC2B457B8E6"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '9562ab63-001c-0009-2eab-ff9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:29 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=properties')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:29 GMT',
  etag: '"0x8D4CDC2B457B8E6"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '9562ab63-001c-0009-2eab-ff9092000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:29 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '4194304',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:52:29 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2B457B8E6"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '613c6d54-001c-000f-39ab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '4194304',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:52:29 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2B457B8E6"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P10',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '613c6d54-001c-000f-39ab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:17 GMT',
  etag: '"0x8D4CDC2AD1EFF21"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '51b9dba7-001c-0008-02ab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:17 GMT',
  etag: '"0x8D4CDC2AD1EFF21"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '51b9dba7-001c-0008-02ab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbfd-001c-0007-1fab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:32 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12fffbfd-001c-0007-1fab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:32 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54f6516e-001c-000e-4eab-ff13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54f6516e-001c-000e-4eab-ff13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:35 GMT',
  etag: '"0x8D4CDC2B7663A4D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fe9fbb2a-001c-0011-42ab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:35 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:35 GMT',
  etag: '"0x8D4CDC2B7663A4D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fe9fbb2a-001c-0011-42ab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:35 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:35 GMT',
  etag: '"0x8D4CDC2B7CCB03D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b511f794-001c-000c-7eab-ffc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:35 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:35 GMT',
  etag: '"0x8D4CDC2B7CCB03D"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'b511f794-001c-000c-7eab-ffc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:35 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:36 GMT',
  etag: '"0x8D4CDC2B85F513E"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '4646bfbb-001c-0004-77ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:36 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:36 GMT',
  etag: '"0x8D4CDC2B85F513E"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '4646bfbb-001c-0004-77ab-ffa1f7000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:36 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Tue, 18 Jul 2017 09:52:40 GMT',
  etag: '"0x8D4CDC2BA9BA0CA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e6a6c288-001c-0006-5aab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:40 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Tue, 18 Jul 2017 09:52:40 GMT',
  etag: '"0x8D4CDC2BA9BA0CA"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'e6a6c288-001c-0006-5aab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:40 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=properties')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:41 GMT',
  etag: '"0x8D4CDC2BB689A5E"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '5f3e546e-001c-000d-78ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:42 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=properties')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:41 GMT',
  etag: '"0x8D4CDC2BB689A5E"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '5f3e546e-001c-000d-78ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:42 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Tue, 18 Jul 2017 09:52:41 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2BB689A5E"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'b511f797-001c-000c-01ab-ffc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Tue, 18 Jul 2017 09:52:41 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2BB689A5E"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': 'b511f797-001c-000c-01ab-ffc918000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:35 GMT',
  etag: '"0x8D4CDC2B7663A4D"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '2266b88e-001c-0005-12ab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:35 GMT',
  etag: '"0x8D4CDC2B7663A4D"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '2266b88e-001c-0005-12ab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9193647b-001c-0014-7eab-ff7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:44 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9193647b-001c-0014-7eab-ff7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:44 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '31edce43-001c-0002-66ab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '31edce43-001c-0002-66ab-ffcffb000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:47 GMT',
  etag: '"0x8D4CDC2BE92D8A7"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '525baeb1-001c-0013-23ab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:47 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:47 GMT',
  etag: '"0x8D4CDC2BE92D8A7"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '525baeb1-001c-0013-23ab-fff258000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:47 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:57 GMT',
  etag: '"0x8D4CDC2C4E54BD4"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'eb2c107f-001c-000b-28ab-ff4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:57 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:57 GMT',
  etag: '"0x8D4CDC2C4E54BD4"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': 'eb2c107f-001c-000b-28ab-ff4a69000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:57 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:58 GMT',
  etag: '"0x8D4CDC2C5816514"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '51b9dbb1-001c-0008-0aab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:58 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:58 GMT',
  etag: '"0x8D4CDC2C5816514"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '51b9dbb1-001c-0008-0aab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:52:58 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata14/archive-blob-testdata15?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Tue, 18 Jul 2017 09:53:02 GMT',
  etag: '"0x8D4CDC2C7A01306"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '12fffc04-001c-0007-23ab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:02 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata14/archive-blob-testdata15?comp=page', '*')
  .reply(201, "", { 'content-md5': 'VJXsRKPJgaTKv8EXnmtrQg==',
  'last-modified': 'Tue, 18 Jul 2017 09:53:02 GMT',
  etag: '"0x8D4CDC2C7A01306"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '12fffc04-001c-0007-23ab-ff9671000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:02 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15?comp=properties')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:03 GMT',
  etag: '"0x8D4CDC2C83F6168"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '54f65185-001c-000e-5eab-ff13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:02 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15?comp=properties')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:03 GMT',
  etag: '"0x8D4CDC2C83F6168"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-blob-sequence-number': '0',
  'x-ms-request-id': '54f65185-001c-000e-5eab-ff13e3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:02 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Tue, 18 Jul 2017 09:53:03 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2C83F6168"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P30',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '5f3e5482-001c-000d-04ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14/archive-blob-testdata15')
  .reply(200, "", { 'content-length': '4194304',
  'last-modified': 'Tue, 18 Jul 2017 09:53:03 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2C83F6168"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-access-tier': 'P30',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '5f3e5482-001c-000d-04ab-ff2465000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:47 GMT',
  etag: '"0x8D4CDC2BE92D8A7"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'd013167b-001c-0000-16ab-ff1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:52:47 GMT',
  etag: '"0x8D4CDC2BE92D8A7"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': 'd013167b-001c-0000-16ab-ff1500000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:05 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata14?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fe9fbb36-001c-0011-4bab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:06 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata14?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fe9fbb36-001c-0011-4bab-ff28a3000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:06 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6a6c290-001c-0006-61ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(404, "", { vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6a6c290-001c-0006-61ab-ff7b0c000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:07 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:09 GMT',
  etag: '"0x8D4CDC2CC228C04"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2266c75c-001c-0005-5dab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:09 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16?restype=container')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:09 GMT',
  etag: '"0x8D4CDC2CC228C04"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2266c75c-001c-0005-5dab-ff4c8a000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:09 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:10 GMT',
  etag: '"0x8D4CDC2CC7E1D36"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '91936c6c-001c-0014-6dab-ff7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17')
  .reply(201, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:10 GMT',
  etag: '"0x8D4CDC2CC7E1D36"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-server-encrypted': 'false',
  'x-ms-request-id': '91936c6c-001c-0014-6dab-ff7129000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:10 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(202, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:11 GMT',
  etag: '"0x8D4CDC2CD1616BE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-status': 'success',
  'x-ms-copy-id': '39822ae4-8252-4239-a720-e7c927e9806d',
  'x-ms-request-id': '81ad8689-001c-0003-38ab-ff2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:11 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .put('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(202, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:11 GMT',
  etag: '"0x8D4CDC2CD1616BE"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-status': 'success',
  'x-ms-copy-id': '39822ae4-8252-4239-a720-e7c927e9806d',
  'x-ms-request-id': '81ad8689-001c-0003-38ab-ff2286000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:11 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:53:11 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2CD1616BE"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-id': '39822ae4-8252-4239-a720-e7c927e9806d',
  'x-ms-copy-progress': '0/0',
  'x-ms-copy-source': 'https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net/archive-cont-testdata16/archive-blob-testdata17',
  'x-ms-copy-status': 'success',
  'x-ms-copy-completion-time': 'Tue, 18 Jul 2017 09:53:11 GMT',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '57131309-001c-000a-28ab-ffa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16/archive-blob-testdata17copied')
  .reply(200, "", { 'content-length': '0',
  'content-type': 'application/octet-stream',
  'last-modified': 'Tue, 18 Jul 2017 09:53:11 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D4CDC2CD1616BE"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-copy-id': '39822ae4-8252-4239-a720-e7c927e9806d',
  'x-ms-copy-progress': '0/0',
  'x-ms-copy-source': 'https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net/archive-cont-testdata16/archive-blob-testdata17',
  'x-ms-copy-status': 'success',
  'x-ms-copy-completion-time': 'Tue, 18 Jul 2017 09:53:11 GMT',
  'x-ms-access-tier': 'P20',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-blob-type': 'PageBlob',
  'x-ms-blob-sequence-number': '0',
  'x-ms-server-encrypted': 'false',
  'x-ms-request-id': '57131309-001c-000a-28ab-ffa714000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:09 GMT',
  etag: '"0x8D4CDC2CC228C04"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '613c6d61-001c-000f-44ab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .head('/archive-cont-testdata16?restype=container')
  .reply(200, "", { 'last-modified': 'Tue, 18 Jul 2017 09:53:09 GMT',
  etag: '"0x8D4CDC2CC228C04"',
  vary: 'Origin',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-lease-state': 'available',
  'x-ms-lease-status': 'unlocked',
  'x-ms-request-id': '613c6d61-001c-000f-44ab-fffe9e000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata16?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51b9dbbb-001c-0008-13ab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:17 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; },
function (nock) { 
var result = 
nock('https://xiaonliprepp.blob.rr1xio.xstore-test.windows-int.net:443')
  .delete('/archive-cont-testdata16?restype=container')
  .reply(202, "", { server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51b9dbbb-001c-0008-13ab-ff7def000000',
  'x-ms-version': '2017-04-17',
  date: 'Tue, 18 Jul 2017 09:53:17 GMT',
  connection: 'close',
  'content-length': '0' });
 return result; }]];