// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xiaonliphputsoutheast;AccountKey=null';
  process.env['AZURE_STORAGE_CONNECTION_STRING_BLOB_ACCOUNT'] = 'DefaultEndpointsProtocol=https;AccountName=xarchivega;AccountKey=null;EndpointSuffix=core.windows.net';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca14fa-001e-0007-71c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca14fa-001e-0007-71c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  etag: '"0x8D537D867CE5E44"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca14ff-001e-0007-73c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata0?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  etag: '"0x8D537D867CE5E44"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca14ff-001e-0007-73c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata0/archive-blob-testdata1', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  etag: '"0x8D537D867847055"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1501-001e-0007-74c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:54:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata0/archive-blob-testdata1', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  etag: '"0x8D537D867847055"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1501-001e-0007-74c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:54:53 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D867847055"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1509-001e-0007-7ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Hot',
  'x-ms-access-tier-inferred': 'true',
  date: 'Thu, 30 Nov 2017 09:54:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata0/archive-blob-testdata1')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D867847055"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1509-001e-0007-7ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Hot',
  'x-ms-access-tier-inferred': 'true',
  date: 'Thu, 30 Nov 2017 09:54:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata0?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata0\"><Blobs><Blob><Name>archive-blob-testdata1</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:53 GMT</Last-Modified><Etag>0x8D537D867847055</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca150f-001e-0007-7dc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata0?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata0\"><Blobs><Blob><Name>archive-blob-testdata1</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:53 GMT</Last-Modified><Etag>0x8D537D867847055</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierInferred>true</AccessTierInferred><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca150f-001e-0007-7dc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  etag: '"0x8D537D867CE5E44"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1512-001e-0007-7fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:54:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata0?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:53 GMT',
  etag: '"0x8D537D867CE5E44"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1512-001e-0007-7fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:54:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1513-001e-0007-80c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata0?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1513-001e-0007-80c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1515-001e-0007-02c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1515-001e-0007-02c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  etag: '"0x8D537D8690C84B0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1518-001e-0007-04c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata2?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  etag: '"0x8D537D8690C84B0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1518-001e-0007-04c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata2/archive-blob-testdata3', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  etag: '"0x8D537D868C05167"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca151c-001e-0007-07c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata2/archive-blob-testdata3', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  etag: '"0x8D537D868C05167"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca151c-001e-0007-07c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:54:55 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca151d-001e-0007-08c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata2/archive-blob-testdata3?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca151d-001e-0007-08c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D868C05167"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca151e-001e-0007-09c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Hot',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:54:55 GMT',
  date: 'Thu, 30 Nov 2017 09:54:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata2/archive-blob-testdata3')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D868C05167"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca151e-001e-0007-09c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Hot',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:54:55 GMT',
  date: 'Thu, 30 Nov 2017 09:54:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:55 GMT</Last-Modified><Etag>0x8D537D868C05167</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierChangeTime>Thu, 30 Nov 2017 09:54:55 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1522-001e-0007-0bc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata2?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata2\"><Blobs><Blob><Name>archive-blob-testdata3</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:55 GMT</Last-Modified><Etag>0x8D537D868C05167</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Hot</AccessTier><AccessTierChangeTime>Thu, 30 Nov 2017 09:54:55 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1522-001e-0007-0bc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  etag: '"0x8D537D8690C84B0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1531-001e-0007-18c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata2?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:55 GMT',
  etag: '"0x8D537D8690C84B0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1531-001e-0007-18c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1534-001e-0007-1ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata2?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1534-001e-0007-1ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1538-001e-0007-1cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1538-001e-0007-1cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata4?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:58 GMT',
  etag: '"0x8D537D86A7564B9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153a-001e-0007-1dc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata4?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:58 GMT',
  etag: '"0x8D537D86A7564B9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153a-001e-0007-1dc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata4/archive-blob-testdata5', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:57 GMT',
  etag: '"0x8D537D86A290FAB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153c-001e-0007-1ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:54:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata4/archive-blob-testdata5', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:57 GMT',
  etag: '"0x8D537D86A290FAB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153c-001e-0007-1ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:54:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153d-001e-0007-1fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata4/archive-blob-testdata5?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153d-001e-0007-1fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:57 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86A290FAB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153e-001e-0007-20c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Cool',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:54:57 GMT',
  date: 'Thu, 30 Nov 2017 09:54:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata4/archive-blob-testdata5')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:57 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86A290FAB"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca153e-001e-0007-20c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Cool',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:54:57 GMT',
  date: 'Thu, 30 Nov 2017 09:54:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata4?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata4\"><Blobs><Blob><Name>archive-blob-testdata5</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:57 GMT</Last-Modified><Etag>0x8D537D86A290FAB</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Cool</AccessTier><AccessTierChangeTime>Thu, 30 Nov 2017 09:54:57 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1545-001e-0007-24c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata4?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata4\"><Blobs><Blob><Name>archive-blob-testdata5</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:57 GMT</Last-Modified><Etag>0x8D537D86A290FAB</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Cool</AccessTier><AccessTierChangeTime>Thu, 30 Nov 2017 09:54:57 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1545-001e-0007-24c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:58 GMT',
  etag: '"0x8D537D86A7564B9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1546-001e-0007-25c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata4?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:54:58 GMT',
  etag: '"0x8D537D86A7564B9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1546-001e-0007-25c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1547-001e-0007-26c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata4?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1547-001e-0007-26c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca154d-001e-0007-29c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca154d-001e-0007-29c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:54:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:00 GMT',
  etag: '"0x8D537D86BDB5E95"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca154f-001e-0007-2ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata6?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:00 GMT',
  etag: '"0x8D537D86BDB5E95"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca154f-001e-0007-2ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata6/archive-blob-testdata7', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:59 GMT',
  etag: '"0x8D537D86B8FD219"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1552-001e-0007-2bc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata6/archive-blob-testdata7', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:59 GMT',
  etag: '"0x8D537D86B8FD219"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1552-001e-0007-2bc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1553-001e-0007-2cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata6/archive-blob-testdata7?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1553-001e-0007-2cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:59 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86B8FD219"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1558-001e-0007-2fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:00 GMT',
  date: 'Thu, 30 Nov 2017 09:55:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata6/archive-blob-testdata7')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:54:59 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86B8FD219"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1558-001e-0007-2fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:00 GMT',
  date: 'Thu, 30 Nov 2017 09:55:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata6?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata6\"><Blobs><Blob><Name>archive-blob-testdata7</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:59 GMT</Last-Modified><Etag>0x8D537D86B8FD219</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><AccessTierChangeTime>Thu, 30 Nov 2017 09:55:00 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca155a-001e-0007-31c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata6?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata6\"><Blobs><Blob><Name>archive-blob-testdata7</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:54:59 GMT</Last-Modified><Etag>0x8D537D86B8FD219</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><AccessTierChangeTime>Thu, 30 Nov 2017 09:55:00 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca155a-001e-0007-31c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:00 GMT',
  etag: '"0x8D537D86BDB5E95"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1564-001e-0007-37c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata6?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:00 GMT',
  etag: '"0x8D537D86BDB5E95"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1564-001e-0007-37c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:01 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca156b-001e-0007-3cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata6?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca156b-001e-0007-3cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca156e-001e-0007-3ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca156e-001e-0007-3ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  etag: '"0x8D537D86D4995C0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1576-001e-0007-43c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata8?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  etag: '"0x8D537D86D4995C0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1576-001e-0007-43c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata8/archive-blob-testdata9', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  etag: '"0x8D537D86CFE0EC9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1581-001e-0007-48c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata8/archive-blob-testdata9', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  etag: '"0x8D537D86CFE0EC9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1581-001e-0007-48c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1590-001e-0007-53c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1590-001e-0007-53c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86CFE0EC9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1598-001e-0007-59c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:02 GMT',
  date: 'Thu, 30 Nov 2017 09:55:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86CFE0EC9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1598-001e-0007-59c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:02 GMT',
  date: 'Thu, 30 Nov 2017 09:55:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15aa-001e-0007-65c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata8/archive-blob-testdata9?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15aa-001e-0007-65c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86CFE0EC9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15c4-001e-0007-74c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:03 GMT',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8/archive-blob-testdata9')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86CFE0EC9"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15c4-001e-0007-74c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:03 GMT',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata8?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata8\"><Blobs><Blob><Name>archive-blob-testdata9</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:55:02 GMT</Last-Modified><Etag>0x8D537D86CFE0EC9</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-hot</ArchiveStatus><AccessTierChangeTime>Thu, 30 Nov 2017 09:55:03 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15d1-001e-0007-7ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata8?restype=container&comp=list&prefix=')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata8\"><Blobs><Blob><Name>archive-blob-testdata9</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:55:02 GMT</Last-Modified><Etag>0x8D537D86CFE0EC9</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-hot</ArchiveStatus><AccessTierChangeTime>Thu, 30 Nov 2017 09:55:03 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15d1-001e-0007-7ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  etag: '"0x8D537D86D4995C0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15d9-001e-0007-05c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata8?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:02 GMT',
  etag: '"0x8D537D86D4995C0"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15d9-001e-0007-05c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15e9-001e-0007-0fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata8?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15e9-001e-0007-0fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:04 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15fe-001e-0007-1cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca15fe-001e-0007-1cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  etag: '"0x8D537D86F11FB5B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1608-001e-0007-23c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata10?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  etag: '"0x8D537D86F11FB5B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1608-001e-0007-23c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  etag: '"0x8D537D86EC6540F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1619-001e-0007-2fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata10/archive-blob-testdata11', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  etag: '"0x8D537D86EC6540F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1619-001e-0007-2fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca162b-001e-0007-38c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:06 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca162b-001e-0007-38c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:06 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86EC6540F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1642-001e-0007-49c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:05 GMT',
  date: 'Thu, 30 Nov 2017 09:55:06 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86EC6540F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1642-001e-0007-49c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:05 GMT',
  date: 'Thu, 30 Nov 2017 09:55:06 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca164d-001e-0007-51c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:06 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata10/archive-blob-testdata11?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca164d-001e-0007-51c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:06 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86EC6540F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca165e-001e-0007-5cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:06 GMT',
  'x-ms-archive-status': 'rehydrate-pending-to-cool',
  date: 'Thu, 30 Nov 2017 09:55:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10/archive-blob-testdata11')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D86EC6540F"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca165e-001e-0007-5cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:06 GMT',
  'x-ms-archive-status': 'rehydrate-pending-to-cool',
  date: 'Thu, 30 Nov 2017 09:55:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata10?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata10\"><Blobs><Blob><Name>archive-blob-testdata11</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:55:05 GMT</Last-Modified><Etag>0x8D537D86EC6540F</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-cool</ArchiveStatus><AccessTierChangeTime>Thu, 30 Nov 2017 09:55:06 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1670-001e-0007-6ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .get('/archive-cont-testdata10?restype=container&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xarchivega.blob.core.windows.net/\" ContainerName=\"archive-cont-testdata10\"><Blobs><Blob><Name>archive-blob-testdata11</Name><Properties><Last-Modified>Thu, 30 Nov 2017 09:55:05 GMT</Last-Modified><Etag>0x8D537D86EC6540F</Etag><Content-Length>17</Content-Length><Content-Type>application/octet-stream</Content-Type><Content-Encoding /><Content-Language /><Content-MD5>cmU6EgPTucj465dn7m3rzg==</Content-MD5><Cache-Control /><Content-Disposition /><BlobType>BlockBlob</BlobType><AccessTier>Archive</AccessTier><ArchiveStatus>rehydrate-pending-to-cool</ArchiveStatus><AccessTierChangeTime>Thu, 30 Nov 2017 09:55:06 GMT</AccessTierChangeTime><LeaseStatus>unlocked</LeaseStatus><LeaseState>available</LeaseState><ServerEncrypted>true</ServerEncrypted></Properties></Blob></Blobs><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1670-001e-0007-6ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  etag: '"0x8D537D86F11FB5B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1680-001e-0007-74c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata10?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:05 GMT',
  etag: '"0x8D537D86F11FB5B"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1680-001e-0007-74c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:07 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1692-001e-0007-7fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata10?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1692-001e-0007-7fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16a0-001e-0007-08c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16a0-001e-0007-08c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  etag: '"0x8D537D870E50F47"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16ae-001e-0007-12c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  etag: '"0x8D537D870E50F47"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16ae-001e-0007-12c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  etag: '"0x8D537D87098AB5A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16c9-001e-0007-25c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata12/archive-blob-testdata13', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  etag: '"0x8D537D87098AB5A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16c9-001e-0007-25c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:08 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16e2-001e-0007-37c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16e2-001e-0007-37c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D87098AB5A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16ee-001e-0007-41c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:08 GMT',
  date: 'Thu, 30 Nov 2017 09:55:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D87098AB5A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca16ee-001e-0007-41c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:08 GMT',
  date: 'Thu, 30 Nov 2017 09:55:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1703-001e-0007-4fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1703-001e-0007-4fc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:09 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D87098AB5A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1719-001e-0007-60c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:09 GMT',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Thu, 30 Nov 2017 09:55:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12/archive-blob-testdata13')
  .reply(200, "", { 'content-length': '17',
  'content-type': 'application/octet-stream',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  'accept-ranges': 'bytes',
  etag: '"0x8D537D87098AB5A"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1719-001e-0007-60c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  'x-ms-blob-type': 'BlockBlob',
  'x-ms-server-encrypted': 'true',
  'x-ms-access-tier': 'Archive',
  'x-ms-access-tier-change-time': 'Thu, 30 Nov 2017 09:55:09 GMT',
  'x-ms-archive-status': 'rehydrate-pending-to-hot',
  date: 'Thu, 30 Nov 2017 09:55:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>BlobBeingRehydrated</Code><Message>This operation is not permitted because the blob is being rehydrated.\nRequestId:0fca172a-001e-0007-6ec1-69fe58000000\nTime:2017-11-30T09:55:10.8726943Z</Message></Error>", { 'content-length': '257',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca172a-001e-0007-6ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata12/archive-blob-testdata13?comp=tier')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>BlobBeingRehydrated</Code><Message>This operation is not permitted because the blob is being rehydrated.\nRequestId:0fca172a-001e-0007-6ec1-69fe58000000\nTime:2017-11-30T09:55:10.8726943Z</Message></Error>", { 'content-length': '257',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca172a-001e-0007-6ec1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  etag: '"0x8D537D870E50F47"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1733-001e-0007-75c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata12?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:08 GMT',
  etag: '"0x8D537D870E50F47"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1733-001e-0007-75c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:10 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1742-001e-0007-02c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata12?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1742-001e-0007-02c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:11 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca174e-001e-0007-0ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca174e-001e-0007-0ac1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata14?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:12 GMT',
  etag: '"0x8D537D872C3E30C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1760-001e-0007-16c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata14?restype=container')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:12 GMT',
  etag: '"0x8D537D872C3E30C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1760-001e-0007-16c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:11 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata14/archive-blob-testdata15', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:11 GMT',
  etag: '"0x8D537D872793414"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1773-001e-0007-24c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/archive-cont-testdata14/archive-blob-testdata15', '*')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'content-md5': 'cmU6EgPTucj465dn7m3rzg==',
  'last-modified': 'Thu, 30 Nov 2017 09:55:11 GMT',
  etag: '"0x8D537D872793414"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1773-001e-0007-24c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-request-server-encrypted': 'true',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15?comp=tier')
  .reply(400, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:0fca1780-001e-0007-2cc1-69fe58000000\nTime:2017-11-30T09:55:12.7257234Z</Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>P10</HeaderValue></Error>", { 'content-length': '325',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1780-001e-0007-2cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .put('/archive-cont-testdata14/archive-blob-testdata15?comp=tier')
  .reply(400, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:0fca1780-001e-0007-2cc1-69fe58000000\nTime:2017-11-30T09:55:12.7257234Z</Message><HeaderName>x-ms-access-tier</HeaderName><HeaderValue>P10</HeaderValue></Error>", { 'content-length': '325',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1780-001e-0007-2cc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:12 GMT',
  etag: '"0x8D537D872C3E30C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1798-001e-0007-3dc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .head('/archive-cont-testdata14?restype=container')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Thu, 30 Nov 2017 09:55:12 GMT',
  etag: '"0x8D537D872C3E30C"',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca1798-001e-0007-3dc1-69fe58000000',
  'x-ms-version': '2017-04-17',
  'x-ms-lease-status': 'unlocked',
  'x-ms-lease-state': 'available',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('http://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata14?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca17a3-001e-0007-45c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xarchivega.blob.core.windows.net:443')
  .delete('/archive-cont-testdata14?restype=container')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0fca17a3-001e-0007-45c1-69fe58000000',
  'x-ms-version': '2017-04-17',
  date: 'Thu, 30 Nov 2017 09:55:12 GMT' });
 return result; }]];