// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xplat;AccountKey=null';
}

exports.scopes = [[function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'expretry1\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6f3f000-0002-001f-56a1-5f6971000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'expretry1\')',
  date: 'Thu, 27 Nov 2014 12:32:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableAlreadyExists</code><message xml:lang=\"en-US\">The table specified already exists.\nRequestId:d152dd5c-0002-0043-6894-99ac2d000000\nTime:2014-11-27T12:32:55.0590182Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd152dd5c-0002-0043-6894-99ac2d000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Thu, 27 Nov 2014 12:32:54 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .get('/Tables(%27expretry1%27)')
  .reply(200, "<?xml version=\"1.0\" encoding=\"utf-8\"?><entry xml:base=\"https://xplat.table.core.windows.net/\" xmlns=\"http://www.w3.org/2005/Atom\" xmlns:d=\"http://schemas.microsoft.com/ado/2007/08/dataservices\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\" xmlns:georss=\"http://www.georss.org/georss\" xmlns:gml=\"http://www.opengis.net/gml\"><id>https://xplat.table.core.windows.net/Tables('expretry1')</id><category term=\"xplat.Tables\" scheme=\"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme\" /><link rel=\"edit\" title=\"Tables\" href=\"Tables('expretry1')\" /><title /><updated>2014-11-27T12:32:56Z</updated><author><name /></author><content type=\"application/xml\"><m:properties><d:TableName>expretry1</d:TableName></m:properties></content></entry>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/atom+xml;type=entry;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f68c62ac-0002-0024-492d-a9501e000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:32:56 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry1%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '236e75e2-0002-0019-245c-dcf786000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:32:55 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'expretry2\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '87433ec6-0002-0022-2ae9-2cf471000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'expretry2\')',
  date: 'Thu, 27 Nov 2014 12:32:57 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry2%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0d65f765-0002-003f-6907-6850f6000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:32:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableBeingDeleted</code><message xml:lang=\"en-US\">The specified table is being deleted. Try operation later.\nRequestId:48cf6821-0002-000c-54df-862267000000\nTime:2014-11-27T12:32:59.0375843Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '48cf6821-0002-000c-54df-862267000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Thu, 27 Nov 2014 12:32:58 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableBeingDeleted</code><message xml:lang=\"en-US\">The specified table is being deleted. Try operation later.\nRequestId:232dbdf4-0002-003d-03ac-bad3f2000000\nTime:2014-11-27T12:33:30.5447762Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '232dbdf4-0002-003d-03ac-bad3f2000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Thu, 27 Nov 2014 12:33:30 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'expretry2\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b6ffe530-0002-0039-558b-e4db76000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'expretry2\')',
  date: 'Thu, 27 Nov 2014 12:33:59 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .get('/Tables(%27expretry2%27)')
  .reply(200, "<?xml version=\"1.0\" encoding=\"utf-8\"?><entry xml:base=\"https://xplat.table.core.windows.net/\" xmlns=\"http://www.w3.org/2005/Atom\" xmlns:d=\"http://schemas.microsoft.com/ado/2007/08/dataservices\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\" xmlns:georss=\"http://www.georss.org/georss\" xmlns:gml=\"http://www.opengis.net/gml\"><id>https://xplat.table.core.windows.net/Tables('expretry2')</id><category term=\"xplat.Tables\" scheme=\"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme\" /><link rel=\"edit\" title=\"Tables\" href=\"Tables('expretry2')\" /><title /><updated>2014-11-27T12:34:00Z</updated><author><name /></author><content type=\"application/xml\"><m:properties><d:TableName>expretry2</d:TableName></m:properties></content></entry>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/atom+xml;type=entry;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6b4ff486-0002-0042-6809-a853c3000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:00 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry2%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12883d11-0002-004b-0ef3-ae098e000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:02 GMT' });
 return result; }],
[function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:b9871bb1-0002-0018-75a9-b3bc33000000\nTime:2014-11-27T12:34:02.9312069Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b9871bb1-0002-0018-75a9-b3bc33000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:02 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:68658411-0002-0021-31c3-d7ec24000000\nTime:2014-11-27T12:34:03.5600051Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '68658411-0002-0021-31c3-d7ec24000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:e6c1375e-0002-002a-169e-ad74f9000000\nTime:2014-11-27T12:34:03.8555503Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6c1375e-0002-002a-169e-ad74f9000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:03 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27expretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:0ae9b9a7-0002-0033-2b27-1d48b0000000\nTime:2014-11-27T12:34:05.2635326Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0ae9b9a7-0002-0033-2b27-1d48b0000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:05 GMT' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .get('/Tables(%27expretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:c552d9ef-0002-0014-4d83-026787000000\nTime:2014-11-27T12:34:05.7003851Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c552d9ef-0002-0014-4d83-026787000000',
  'x-ms-version': '2014-02-14',
  'x-content-type-options': 'nosniff',
  date: 'Thu, 27 Nov 2014 12:34:04 GMT' });
 return result; }]];