// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xplat;AccountKey=null';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fc75aff6-001a-0005-4c70-6d6278000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fc75aff6-001a-0005-4c70-6d6278000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1?restype=share')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:18 GMT',
  etag: '"0x8D43B876C03E79B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1a5ad726-001a-000e-0670-6d7a0c000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1?restype=share')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:18 GMT',
  etag: '"0x8D43B876C03E79B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1a5ad726-001a-000e-0670-6d7a0c000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ebc655ca-001a-0017-7170-6d5664000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ebc655ca-001a-0017-7170-6d5664000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:19 GMT',
  etag: '"0x8D43B876C7AC70E"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e89fc52a-001a-0034-4170-6d39af000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:19 GMT',
  etag: '"0x8D43B876C7AC70E"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e89fc52a-001a-0034-4170-6d39af000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:19 GMT',
  etag: '"0x8D43B876C7AC70E"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd6b1ddda-001a-0029-0770-6de045000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:19 GMT',
  etag: '"0x8D43B876C7AC70E"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd6b1ddda-001a-0029-0770-6de045000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:18 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:20 GMT',
  etag: '"0x8D43B876D052E8A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7799f2c9-001a-000a-5770-6d8f8e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:20 GMT',
  etag: '"0x8D43B876D052E8A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7799f2c9-001a-000a-5770-6d8f8e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:19 GMT',
  connection: 'close' });
 return result; }],
[],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:20 GMT',
  etag: '"0x8D43B876D4FF465"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f64a3946-001a-001c-2570-6d4e10000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:20 GMT',
  etag: '"0x8D43B876D4FF465"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f64a3946-001a-001c-2570-6d4e10000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:f3f433b7-001a-0010-0f70-6da0e1000000\nTime:2017-01-13T07:40:21.8866663Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f3f433b7-001a-0010-0f70-6da0e1000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:f3f433b7-001a-0010-0f70-6da0e1000000\nTime:2017-01-13T07:40:21.8866663Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f3f433b7-001a-0010-0f70-6da0e1000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '50af8b73-001a-0006-4b70-6d617f000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '50af8b73-001a-0006-4b70-6d617f000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:22 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:22 GMT',
  etag: '"0x8D43B876E7F5112"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'db007130-001a-004a-3e70-6da660000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:22 GMT',
  etag: '"0x8D43B876E7F5112"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'db007130-001a-004a-3e70-6da660000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:f2154676-001a-003e-7570-6d2026000000\nTime:2017-01-13T07:40:23.6949663Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f2154676-001a-003e-7570-6d2026000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:f2154676-001a-003e-7570-6d2026000000\nTime:2017-01-13T07:40:23.6949663Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f2154676-001a-003e-7570-6d2026000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b4f4d5a0-001a-0046-6970-6d4891000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b4f4d5a0-001a-0046-6970-6d4891000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:23 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'adbfc024-001a-003c-5670-6d22dc000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'adbfc024-001a-003c-5670-6d22dc000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:24 GMT',
  etag: '"0x8D43B876FDAA062"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '18a30be8-001a-0030-0b70-6dcc2d000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:24 GMT',
  etag: '"0x8D43B876FDAA062"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '18a30be8-001a-0030-0b70-6dcc2d000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:24 GMT',
  etag: '"0x8D43B876FDAA062"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '38a75c6e-001a-002e-2270-6d16c0000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:24 GMT',
  etag: '"0x8D43B876FDAA062"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '38a75c6e-001a-002e-2270-6d16c0000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:24 GMT',
  etag: '"0x8D43B876FDAA062"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '79143860-001a-0040-3770-6dbfe9000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:24 GMT',
  etag: '"0x8D43B876FDAA062"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '79143860-001a-0040-3770-6dbfe9000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd0174115-001a-0049-6470-6da567000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd0174115-001a-0049-6470-6da567000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '376ec283-001a-0016-5b70-6d5799000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '376ec283-001a-0016-5b70-6d5799000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:26 GMT',
  connection: 'close' });
 return result; }],
[],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0154fde7-001a-000b-1670-6d8e73000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0154fde7-001a-000b-1670-6d8e73000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9e3ae2b2-001a-0028-6870-6de1b8000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9e3ae2b2-001a-0028-6870-6de1b8000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:28 GMT',
  etag: '"0x8D43B8771B29BB0"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5845c58-001a-0031-4370-6dcdd0000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:28 GMT',
  etag: '"0x8D43B8771B29BB0"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f5845c58-001a-0031-4370-6dcdd0000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:28 GMT',
  etag: '"0x8D43B8771B29BB0"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4480449a-001a-0012-0970-6da21b000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:28 GMT',
  etag: '"0x8D43B8771B29BB0"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4480449a-001a-0012-0970-6da21b000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e7dc44a5-001a-001b-1570-6db895000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e7dc44a5-001a-001b-1570-6db895000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3b9ed23f-001a-004c-2470-6d5118000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3b9ed23f-001a-004c-2470-6d5118000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:28 GMT',
  connection: 'close' });
 return result; }],
[],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cc2af6b8-001a-0036-7c70-6d3b55000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cc2af6b8-001a-0036-7c70-6d3b55000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:30 GMT',
  etag: '"0x8D43B8772FFBA01"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '725b46b8-001a-002b-3570-6de2bf000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:30 GMT',
  etag: '"0x8D43B8772FFBA01"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '725b46b8-001a-002b-3570-6de2bf000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:30 GMT',
  etag: '"0x8D43B8772FFBA01"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f11ae2e1-001a-0020-2a70-6dfacb000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:30 GMT',
  etag: '"0x8D43B8772FFBA01"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f11ae2e1-001a-0020-2a70-6dfacb000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '99fa1e8f-001a-0001-3b70-6d97fa000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '99fa1e8f-001a-0001-3b70-6d97fa000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:30 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:20 GMT',
  etag: '"0x8D43B876D052E8A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2d99ac7d-001a-0032-0770-6dced7000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:20 GMT',
  etag: '"0x8D43B876D052E8A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2d99ac7d-001a-0032-0770-6dced7000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:30 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3437e435-001a-0008-1c70-6d8d74000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3437e435-001a-0008-1c70-6d8d74000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:32 GMT',
  etag: '"0x8D43B87744FBEAA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ca7bd9fe-001a-004d-7c70-6d50e5000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:32 GMT',
  etag: '"0x8D43B87744FBEAA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ca7bd9fe-001a-004d-7c70-6d50e5000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata18?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata18\"><Entries /><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51d92154-001a-001a-4f70-6db968000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata18?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata18\"><Entries /><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '51d92154-001a-001a-4f70-6db968000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:32 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9438cee3-001a-0035-2c70-6d3852000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9438cee3-001a-0035-2c70-6d3852000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:33 GMT',
  etag: '"0x8D43B8775177E6D"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd621dd91-001a-0002-0a70-6d94fd000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:33 GMT',
  etag: '"0x8D43B8775177E6D"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd621dd91-001a-0002-0a70-6d94fd000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:34 GMT',
  etag: '"0x8D43B87755AC9D6"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c6e3680c-001a-0047-4670-6d496c000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:34 GMT',
  etag: '"0x8D43B87755AC9D6"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c6e3680c-001a-0047-4670-6d496c000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata19?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata19\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '39c30c72-001a-002f-5270-6d173d000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata19?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata19\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '39c30c72-001a-002f-5270-6d173d000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:34 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cb1cf80c-001a-000f-1470-6d7bf1000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cb1cf80c-001a-000f-1470-6d7bf1000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:35 GMT',
  etag: '"0x8D43B8776265A29"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b5e541b2-001a-0041-7470-6dbe14000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:35 GMT',
  etag: '"0x8D43B8776265A29"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b5e541b2-001a-0041-7470-6dbe14000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:35 GMT',
  etag: '"0x8D43B87766D0155"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a3d7349f-001a-001f-5770-6d4d17000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:35 GMT',
  etag: '"0x8D43B87766D0155"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a3d7349f-001a-001f-5770-6d4d17000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata20?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata20\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0c8d4692-001a-0015-4870-6d549e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata20?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata20\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0c8d4692-001a-0015-4870-6d549e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:35 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5cf2b55f-001a-0009-2970-6d8c89000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5cf2b55f-001a-0009-2970-6d8c89000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:37 GMT',
  etag: '"0x8D43B87773CB052"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54fb225f-001a-0026-0370-6d0db3000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:37 GMT',
  etag: '"0x8D43B87773CB052"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54fb225f-001a-0026-0370-6d0db3000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:37 GMT',
  etag: '"0x8D43B877780BF39"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54c14246-001a-0043-3e70-6dbcee000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:37 GMT',
  etag: '"0x8D43B877780BF39"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '54c14246-001a-0043-3e70-6dbcee000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:37 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata15?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:38 GMT',
  etag: '"0x8D43B8777C3BCAA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '53c5be52-001a-0024-7a70-6d0f49000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata15?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:38 GMT',
  etag: '"0x8D43B8777C3BCAA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '53c5be52-001a-0024-7a70-6d0f49000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:38 GMT',
  etag: '"0x8D43B877805818F"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'bc6c1b02-001a-0019-1770-6dba6f000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:38 GMT',
  etag: '"0x8D43B877805818F"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'bc6c1b02-001a-0019-1770-6dba6f000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata17')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:39 GMT',
  etag: '"0x8D43B87784B1715"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '86e75e9c-001a-000c-0470-6d78f6000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata17')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:39 GMT',
  etag: '"0x8D43B87784B1715"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '86e75e9c-001a-000c-0470-6d78f6000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata21?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata21\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory><Directory><Name>dir-testdata15</Name><Properties /></Directory><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><File><Name>file-testdata17</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '13f8a3cf-001a-003d-5a70-6d2321000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata21?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata21\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory><Directory><Name>dir-testdata15</Name><Properties /></Directory><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><File><Name>file-testdata17</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '13f8a3cf-001a-003d-5a70-6d2321000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:39 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6e2bf564-001a-001e-6770-6d4cea000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6e2bf564-001a-001e-6770-6d4cea000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:40 GMT',
  etag: '"0x8D43B87791C73D8"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '49f558de-001a-0027-4d70-6d0c4e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:40 GMT',
  etag: '"0x8D43B87791C73D8"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '49f558de-001a-0027-4d70-6d0c4e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:40 GMT',
  etag: '"0x8D43B8779627E8A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '64cf0f60-001a-0044-7670-6d4a6b000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:40 GMT',
  etag: '"0x8D43B8779627E8A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '64cf0f60-001a-0044-7670-6d4a6b000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '81a64b39-001a-0039-5570-6dd6a3000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '81a64b39-001a-0039-5570-6dd6a3000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/next?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:41 GMT',
  etag: '"0x8D43B8779E76806"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8fe36ba4-001a-0042-1770-6dbd13000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/next?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:41 GMT',
  etag: '"0x8D43B8779E76806"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8fe36ba4-001a-0042-1770-6dbd13000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><Directory><Name>next</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c1b69610-001a-004b-5370-6da79d000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><Directory><Name>next</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c1b69610-001a-004b-5370-6da79d000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:42 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata23?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ae164eea-001a-0018-0970-6dbb92000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata23?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ae164eea-001a-0018-0970-6dbb92000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata23?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:43 GMT',
  etag: '"0x8D43B877AB31F6E"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e885d188-001a-002a-4970-6de342000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata23?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:43 GMT',
  etag: '"0x8D43B877AB31F6E"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e885d188-001a-002a-4970-6de342000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata24?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:43 GMT',
  etag: '"0x8D43B877AF6B91F"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '43ba34ea-001a-0033-4c70-6dcf2a000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata24?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:43 GMT',
  etag: '"0x8D43B877AF6B91F"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '43ba34ea-001a-0033-4c70-6dcf2a000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata25?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:44 GMT',
  etag: '"0x8D43B877B391A51"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '973208c5-001a-0014-0670-6d5563000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata25?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:44 GMT',
  etag: '"0x8D43B877B391A51"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '973208c5-001a-0014-0670-6d5563000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata26')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:44 GMT',
  etag: '"0x8D43B877B7BC9A3"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f9e07793-001a-0045-1770-6d4b96000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata26')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:44 GMT',
  etag: '"0x8D43B877B7BC9A3"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f9e07793-001a-0045-1770-6d4b96000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata27')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:44 GMT',
  etag: '"0x8D43B877BBE03B3"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cebff913-001a-003a-6e70-6dd5a4000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/prefixtest-testdata27')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:44 GMT',
  etag: '"0x8D43B877BBE03B3"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cebff913-001a-003a-6e70-6dd5a4000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1?restype=directory&comp=list&prefix=prefixtest-')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"\"><Prefix>prefixtest-</Prefix><Entries><Directory><Name>prefixtest-testdata24</Name><Properties /></Directory><Directory><Name>prefixtest-testdata25</Name><Properties /></Directory><File><Name>prefixtest-testdata26</Name><Properties><Content-Length>0</Content-Length></Properties></File><File><Name>prefixtest-testdata27</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '629b08e9-001a-0007-6f70-6d6082000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1?restype=directory&comp=list&prefix=prefixtest-')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"\"><Prefix>prefixtest-</Prefix><Entries><Directory><Name>prefixtest-testdata24</Name><Properties /></Directory><Directory><Name>prefixtest-testdata25</Name><Properties /></Directory><File><Name>prefixtest-testdata26</Name><Properties><Content-Length>0</Content-Length></Properties></File><File><Name>prefixtest-testdata27</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '629b08e9-001a-0007-6f70-6d6082000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:45 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata28?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:45 GMT',
  etag: '"0x8D43B877C4955CF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25b87406-001a-0038-4a70-6dd75e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata28?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:45 GMT',
  etag: '"0x8D43B877C4955CF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '25b87406-001a-0038-4a70-6dd75e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata28?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:46 GMT',
  etag: '"0x8D43B877C994BAE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fc75b015-001a-0005-5470-6d6278000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata28?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:46 GMT',
  etag: '"0x8D43B877C994BAE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fc75b015-001a-0005-5470-6d6278000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata28?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:46 GMT',
  etag: '"0x8D43B877C994BAE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1a5ad742-001a-000e-0d70-6d7a0c000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-class': 'Test',
  date: 'Fri, 13 Jan 2017 07:40:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata28?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:46 GMT',
  etag: '"0x8D43B877C994BAE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1a5ad742-001a-000e-0d70-6d7a0c000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-class': 'Test',
  date: 'Fri, 13 Jan 2017 07:40:46 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata29?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:47 GMT',
  etag: '"0x8D43B877D29A6EF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ebc655ef-001a-0017-7970-6d5664000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata29?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:47 GMT',
  etag: '"0x8D43B877D29A6EF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ebc655ef-001a-0017-7970-6d5664000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata29?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:47 GMT',
  etag: '"0x8D43B877D29A6EF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e89fc549-001a-0034-4970-6d39af000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-class': 'Test',
  date: 'Fri, 13 Jan 2017 07:40:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata29?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:47 GMT',
  etag: '"0x8D43B877D29A6EF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e89fc549-001a-0034-4970-6d39af000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-class': 'Test',
  date: 'Fri, 13 Jan 2017 07:40:47 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata30?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:48 GMT',
  etag: '"0x8D43B877DB7B837"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd6b1ddfb-001a-0029-0e70-6de045000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata30?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:48 GMT',
  etag: '"0x8D43B877DB7B837"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd6b1ddfb-001a-0029-0e70-6de045000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata30?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:48 GMT',
  etag: '"0x8D43B877DFB790B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7799f2e9-001a-000a-5d70-6d8f8e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata30?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:48 GMT',
  etag: '"0x8D43B877DFB790B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7799f2e9-001a-000a-5d70-6d8f8e000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata30?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:48 GMT',
  etag: '"0x8D43B877DFB790B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e778af5e-001a-003b-6870-6dd459000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-color': 'Blue',
  date: 'Fri, 13 Jan 2017 07:40:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata30?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:48 GMT',
  etag: '"0x8D43B877DFB790B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e778af5e-001a-003b-6870-6dd459000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-color': 'Blue',
  date: 'Fri, 13 Jan 2017 07:40:48 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata31?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:49 GMT',
  etag: '"0x8D43B877E867CF9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f64a396a-001a-001c-2d70-6d4e10000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata31?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:49 GMT',
  etag: '"0x8D43B877E867CF9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f64a396a-001a-001c-2d70-6d4e10000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata31?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:50 GMT',
  etag: '"0x8D43B877ED5617A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f3f433d9-001a-0010-1a70-6da0e1000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata31?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:50 GMT',
  etag: '"0x8D43B877ED5617A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f3f433d9-001a-0010-1a70-6da0e1000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata31?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:50 GMT',
  etag: '"0x8D43B877ED5617A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '50af8b9a-001a-0006-5370-6d617f000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-class': 'Test',
  date: 'Fri, 13 Jan 2017 07:40:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata31?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:50 GMT',
  etag: '"0x8D43B877ED5617A"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '50af8b9a-001a-0006-5370-6d617f000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-class': 'Test',
  date: 'Fri, 13 Jan 2017 07:40:50 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata32?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:50 GMT',
  etag: '"0x8D43B877F63C0FE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'db007156-001a-004a-4670-6da660000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata32?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:50 GMT',
  etag: '"0x8D43B877F63C0FE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'db007156-001a-004a-4670-6da660000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata32?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:51 GMT',
  etag: '"0x8D43B877FAE3883"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a99243bd-001a-0004-0170-6d6385000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata32?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:51 GMT',
  etag: '"0x8D43B877FAE3883"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a99243bd-001a-0004-0170-6d6385000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata32?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:51 GMT',
  etag: '"0x8D43B877FAE3883"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f81cb5df-001a-0048-5670-6da49a000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-color': 'blue,Orange,Red',
  date: 'Fri, 13 Jan 2017 07:40:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata32?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:51 GMT',
  etag: '"0x8D43B877FAE3883"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f81cb5df-001a-0048-5670-6da49a000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-color': 'blue,Orange,Red',
  date: 'Fri, 13 Jan 2017 07:40:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata32?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:52 GMT',
  etag: '"0x8D43B8780362F24"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f215469d-001a-003e-7c70-6d2026000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata32?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:52 GMT',
  etag: '"0x8D43B8780362F24"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f215469d-001a-003e-7c70-6d2026000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata32?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:52 GMT',
  etag: '"0x8D43B8780362F24"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b4f4d5c8-001a-0046-7070-6d4891000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-color': 'white,BLACK',
  date: 'Fri, 13 Jan 2017 07:40:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata32?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:52 GMT',
  etag: '"0x8D43B8780362F24"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b4f4d5c8-001a-0046-7070-6d4891000000',
  'x-ms-version': '2016-05-31',
  'x-ms-meta-color': 'white,BLACK',
  date: 'Fri, 13 Jan 2017 07:40:52 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:18 GMT',
  etag: '"0x8D43B876C03E79B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd2eefc36-001a-0011-6270-6da11c000000',
  'x-ms-version': '2016-05-31',
  'x-ms-share-quota': '5120',
  date: 'Fri, 13 Jan 2017 07:40:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Fri, 13 Jan 2017 07:40:18 GMT',
  etag: '"0x8D43B876C03E79B"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd2eefc36-001a-0011-6270-6da11c000000',
  'x-ms-version': '2016-05-31',
  'x-ms-share-quota': '5120',
  date: 'Fri, 13 Jan 2017 07:40:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1?restype=share')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c71aa1a8-001a-0037-7b70-6d3aa8000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1?restype=share')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c71aa1a8-001a-0037-7b70-6d3aa8000000',
  'x-ms-version': '2016-05-31',
  date: 'Fri, 13 Jan 2017 07:40:53 GMT',
  connection: 'close' });
 return result; }]];