// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xplat;AccountKey=null';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '44743009-001a-0028-4f1f-83e1b8000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '44743009-001a-0028-4f1f-83e1b8000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1?restype=share')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:22 GMT',
  etag: '"0x8D3513633861736"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21b94f07-001a-0006-791f-83617f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1?restype=share')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:22 GMT',
  etag: '"0x8D3513633861736"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21b94f07-001a-0006-791f-83617f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:22 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '03e56f44-001a-004b-661f-83a79d000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '03e56f44-001a-004b-661f-83a79d000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:22 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:24 GMT',
  etag: '"0x8D351363495C935"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c32d3f76-001a-0014-571f-835563000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:24 GMT',
  etag: '"0x8D351363495C935"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c32d3f76-001a-0014-571f-835563000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:24 GMT',
  etag: '"0x8D351363495C935"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1ce88381-001a-0019-0f1f-83ba6f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata2?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:24 GMT',
  etag: '"0x8D351363495C935"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1ce88381-001a-0019-0f1f-83ba6f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:24 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:25 GMT',
  etag: '"0x8D35136357582B6"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f77eb02f-001a-0032-641f-83ced7000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:25 GMT',
  etag: '"0x8D35136357582B6"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f77eb02f-001a-0032-641f-83ced7000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:24 GMT',
  connection: 'close' });
 return result; }],
[],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:26 GMT',
  etag: '"0x8D3513635D66AA4"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '670df3e9-001a-0023-151f-83f9cc000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:26 GMT',
  etag: '"0x8D3513635D66AA4"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '670df3e9-001a-0023-151f-83f9cc000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:25 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:d48b6e72-001a-0000-341f-839607000000\nTime:2016-03-21T03:09:27.3699984Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd48b6e72-001a-0000-341f-839607000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:d48b6e72-001a-0000-341f-839607000000\nTime:2016-03-21T03:09:27.3699984Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd48b6e72-001a-0000-341f-839607000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21d36d91-001a-002d-4d1f-8315c7000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata5?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21d36d91-001a-002d-4d1f-8315c7000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:27 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:28 GMT',
  etag: '"0x8D3513637699BB3"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '536379b6-001a-000a-261f-838f8e000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:28 GMT',
  etag: '"0x8D3513637699BB3"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '536379b6-001a-000a-261f-838f8e000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:27 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:ee034817-001a-004a-571f-83a660000000\nTime:2016-03-21T03:09:29.1541145Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ee034817-001a-004a-571f-83a660000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(409, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ResourceAlreadyExists</Code><Message>The specified resource already exists.\nRequestId:ee034817-001a-004a-571f-83a660000000\nTime:2016-03-21T03:09:29.1541145Z</Message></Error>", { 'content-length': '228',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ee034817-001a-004a-571f-83a660000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '45991b54-001a-003c-411f-8322dc000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata7/?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '45991b54-001a-003c-411f-8322dc000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:29 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a2480038-001a-0041-0f1f-83be14000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a2480038-001a-0041-0f1f-83be14000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:29 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:31 GMT',
  etag: '"0x8D3513638D6CCDA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f687bd85-001a-0009-401f-838c89000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:31 GMT',
  etag: '"0x8D3513638D6CCDA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f687bd85-001a-0009-401f-838c89000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:31 GMT',
  etag: '"0x8D3513638D6CCDA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb0ea442-001a-0022-5a1f-83f831000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:31 GMT',
  etag: '"0x8D3513638D6CCDA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb0ea442-001a-0022-5a1f-83f831000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:31 GMT',
  etag: '"0x8D3513638D6CCDA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fb66ca1b-001a-0027-4c1f-830c4e000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:31 GMT',
  etag: '"0x8D3513638D6CCDA"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'fb66ca1b-001a-0027-4c1f-830c4e000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a1851346-001a-0040-131f-83bfe9000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a1851346-001a-0040-131f-83bfe9000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'dc5957d7-001a-0031-741f-83cdd0000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata8?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'dc5957d7-001a-0031-741f-83cdd0000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:32 GMT',
  connection: 'close' });
 return result; }],
[],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c3d49574-001a-0036-601f-833b55000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c3d49574-001a-0036-601f-833b55000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '632d017f-001a-0013-7b1f-83a3e6000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '632d017f-001a-0013-7b1f-83a3e6000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:35 GMT',
  etag: '"0x8D351363B579A79"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '76020be9-001a-002c-4c1f-83143a000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:35 GMT',
  etag: '"0x8D351363B579A79"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '76020be9-001a-002c-4c1f-83143a000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:35 GMT',
  etag: '"0x8D351363B579A79"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4cc052cb-001a-0004-061f-836385000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:35 GMT',
  etag: '"0x8D351363B579A79"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4cc052cb-001a-0004-061f-836385000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:35 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1d2f1bfe-001a-001d-021f-834fed000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1d2f1bfe-001a-001d-021f-834fed000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '012615a2-001a-000d-781f-83790b000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata10?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '012615a2-001a-000d-781f-83790b000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:36 GMT',
  connection: 'close' });
 return result; }],
[],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'be668d13-001a-0012-3c1f-83a21b000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'be668d13-001a-0012-3c1f-83a21b000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:38 GMT',
  etag: '"0x8D351363D2D552C"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '316b35d2-001a-003f-561f-8321db000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:38 GMT',
  etag: '"0x8D351363D2D552C"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '316b35d2-001a-003f-561f-8321db000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:38 GMT',
  etag: '"0x8D351363D2D552C"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '64c01030-001a-0030-0d1f-83cc2d000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:38 GMT',
  etag: '"0x8D351363D2D552C"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '64c01030-001a-0030-0d1f-83cc2d000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd9158618-001a-0049-321f-83a567000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:38 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1/dir-testdata12?restype=directory')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd9158618-001a-0049-321f-83a567000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:38 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:25 GMT',
  etag: '"0x8D35136357582B6"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a35f527b-001a-003a-5d1f-83d5a4000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:25 GMT',
  etag: '"0x8D35136357582B6"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a35f527b-001a-003a-5d1f-83d5a4000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:39 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '603c29b8-001a-0021-741f-83fb36000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '603c29b8-001a-0021-741f-83fb36000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:39 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:41 GMT',
  etag: '"0x8D351363EFC31BE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '153b450d-001a-0025-601f-830eb4000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata18?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:41 GMT',
  etag: '"0x8D351363EFC31BE"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '153b450d-001a-0025-601f-830eb4000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata18?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata18\"><Entries /><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4dfb7d0-001a-0008-521f-838d74000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata18?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata18\"><Entries /><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e4dfb7d0-001a-0008-521f-838d74000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:41 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7556213b-001a-0035-521f-833852000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7556213b-001a-0035-521f-833852000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:43 GMT',
  etag: '"0x8D35136400DF958"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb96a2f7-001a-0016-4c1f-835799000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:43 GMT',
  etag: '"0x8D35136400DF958"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'eb96a2f7-001a-0016-4c1f-835799000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:43 GMT',
  etag: '"0x8D3513640676719"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '29c76890-001a-001c-551f-834e10000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata19/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:43 GMT',
  etag: '"0x8D3513640676719"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '29c76890-001a-001c-551f-834e10000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:42 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata19?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata19\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6cbcb9aa-001a-0048-5a1f-83a49a000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata19?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata19\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6cbcb9aa-001a-0048-5a1f-83a49a000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:44 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5a7ad168-001a-0039-0c1f-83d6a3000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '5a7ad168-001a-0039-0c1f-83d6a3000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:45 GMT',
  etag: '"0x8D3513641790798"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f596c3e5-001a-002a-741f-83e342000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:45 GMT',
  etag: '"0x8D3513641790798"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'f596c3e5-001a-002a-741f-83e342000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:46 GMT',
  etag: '"0x8D3513641D3FBFD"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '07eea808-001a-0043-0d1f-83bcee000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata20/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:46 GMT',
  etag: '"0x8D3513641D3FBFD"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '07eea808-001a-0043-0d1f-83bcee000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata20?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata20\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2e4ea4dc-001a-000c-741f-8378f6000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata20?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata20\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2e4ea4dc-001a-000c-741f-8378f6000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:46 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3c7f9ff0-001a-004d-571f-8350e5000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3c7f9ff0-001a-004d-571f-8350e5000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:48 GMT',
  etag: '"0x8D3513642E2B641"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b93cc4ef-001a-0002-6d1f-8394fd000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:48 GMT',
  etag: '"0x8D3513642E2B641"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'b93cc4ef-001a-0002-6d1f-8394fd000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:48 GMT',
  etag: '"0x8D35136433EBC30"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3df7d19e-001a-001b-331f-83b895000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata14?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:48 GMT',
  etag: '"0x8D35136433EBC30"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3df7d19e-001a-001b-331f-83b895000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata15?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:49 GMT',
  etag: '"0x8D3513643991449"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '360e4f03-001a-0034-451f-8339af000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/dir-testdata15?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:49 GMT',
  etag: '"0x8D3513643991449"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '360e4f03-001a-0034-451f-8339af000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:49 GMT',
  etag: '"0x8D3513643F36C59"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6ee8ecd-001a-0010-7b1f-83a0e1000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:49 GMT',
  etag: '"0x8D3513643F36C59"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e6ee8ecd-001a-0010-7b1f-83a0e1000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata17')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:50 GMT',
  etag: '"0x8D35136444D0123"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6befc294-001a-001f-1f1f-834d17000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata21/file-testdata17')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:50 GMT',
  etag: '"0x8D35136444D0123"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6befc294-001a-001f-1f1f-834d17000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:49 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata21?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata21\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory><Directory><Name>dir-testdata15</Name><Properties /></Directory><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><File><Name>file-testdata17</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '17d52fee-001a-0024-2b1f-830f49000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata21?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata21\"><Entries><Directory><Name>dir-testdata14</Name><Properties /></Directory><Directory><Name>dir-testdata15</Name><Properties /></Directory><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><File><Name>file-testdata17</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '17d52fee-001a-0024-2b1f-830f49000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:50 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2a64abdb-001a-003d-3b1f-832321000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(404, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2a64abdb-001a-003d-3b1f-832321000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:52 GMT',
  etag: '"0x8D35136456335BC"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c98e241b-001a-002f-351f-83173d000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:52 GMT',
  etag: '"0x8D35136456335BC"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c98e241b-001a-002f-351f-83173d000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:52 GMT',
  etag: '"0x8D3513645BFB0CF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '78591b95-001a-000b-211f-838e73000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/file-testdata16')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:52 GMT',
  etag: '"0x8D3513645BFB0CF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '78591b95-001a-000b-211f-838e73000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:52 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '78c0266a-001a-0001-551f-8397fa000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '78c0266a-001a-0001-551f-8397fa000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/next?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:54 GMT',
  etag: '"0x8D35136467376B2"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0bdfc07e-001a-002e-141f-8316c0000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata22/next?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:54 GMT',
  etag: '"0x8D35136467376B2"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '0bdfc07e-001a-002e-141f-8316c0000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><Directory><Name>next</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '86d09871-001a-0033-381f-83cf2a000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .get('/directory-test-share-testdata1/dir-testdata22?restype=directory&comp=list')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><EnumerationResults ServiceEndpoint=\"https://xplat.file.core.windows.net/\" ShareName=\"directory-test-share-testdata1\" DirectoryPath=\"dir-testdata22\"><Entries><File><Name>file-testdata16</Name><Properties><Content-Length>0</Content-Length></Properties></File><Directory><Name>next</Name><Properties /></Directory></Entries><NextMarker /></EnumerationResults>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '86d09871-001a-0033-381f-83cf2a000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:53 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata23?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:55 GMT',
  etag: '"0x8D35136472FA144"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '85b3aed0-001a-0038-7c1f-83d75e000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata23?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:55 GMT',
  etag: '"0x8D35136472FA144"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '85b3aed0-001a-0038-7c1f-83d75e000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:54 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata23?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:55 GMT',
  etag: '"0x8D35136478BA737"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd7852c84-001a-0029-561f-83e045000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata23?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:55 GMT',
  etag: '"0x8D35136478BA737"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd7852c84-001a-0029-561f-83e045000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata23?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:55 GMT',
  etag: '"0x8D35136478BA737"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4f8f0a57-001a-0047-3c1f-83496c000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-class': 'Test',
  date: 'Mon, 21 Mar 2016 03:09:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata23?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:55 GMT',
  etag: '"0x8D35136478BA737"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4f8f0a57-001a-0047-3c1f-83496c000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-class': 'Test',
  date: 'Mon, 21 Mar 2016 03:09:55 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata24?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:57 GMT',
  etag: '"0x8D351364847D1B7"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cc29927a-001a-000f-5c1f-837bf1000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:56 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata24?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:57 GMT',
  etag: '"0x8D351364847D1B7"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cc29927a-001a-000f-5c1f-837bf1000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:56 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata24?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:57 GMT',
  etag: '"0x8D351364847D1B7"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3cd86792-001a-0015-421f-83549e000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-class': 'Test',
  date: 'Mon, 21 Mar 2016 03:09:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata24?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:57 GMT',
  etag: '"0x8D351364847D1B7"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3cd86792-001a-0015-421f-83549e000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-class': 'Test',
  date: 'Mon, 21 Mar 2016 03:09:57 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata25?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:58 GMT',
  etag: '"0x8D3513648FB9784"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '267cf062-001a-001a-2c1f-83b968000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata25?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:58 GMT',
  etag: '"0x8D3513648FB9784"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '267cf062-001a-001a-2c1f-83b968000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata25?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:58 GMT',
  etag: '"0x8D351364955A1B4"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2ba3ffdb-001a-0046-731f-834891000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata25?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:58 GMT',
  etag: '"0x8D351364955A1B4"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '2ba3ffdb-001a-0046-731f-834891000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata25?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:58 GMT',
  etag: '"0x8D351364955A1B4"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8439b66f-001a-0037-2c1f-833aa8000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-color': 'Blue',
  date: 'Mon, 21 Mar 2016 03:09:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata25?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:58 GMT',
  etag: '"0x8D351364955A1B4"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '8439b66f-001a-0037-2c1f-833aa8000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-color': 'Blue',
  date: 'Mon, 21 Mar 2016 03:09:58 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata26?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:00 GMT',
  etag: '"0x8D351364A0DD453"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '44743034-001a-0028-571f-83e1b8000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata26?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:00 GMT',
  etag: '"0x8D351364A0DD453"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '44743034-001a-0028-571f-83e1b8000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:09:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata26?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:00 GMT',
  etag: '"0x8D351364A69B323"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21b94f29-001a-0006-801f-83617f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata26?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:00 GMT',
  etag: '"0x8D351364A69B323"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21b94f29-001a-0006-801f-83617f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata26?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:00 GMT',
  etag: '"0x8D351364A69B323"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7bbac6f7-001a-001e-6a1f-834cea000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-class': 'Test',
  date: 'Mon, 21 Mar 2016 03:10:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata26?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:00 GMT',
  etag: '"0x8D351364A69B323"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '7bbac6f7-001a-001e-6a1f-834cea000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-class': 'Test',
  date: 'Mon, 21 Mar 2016 03:10:01 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata27?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:02 GMT',
  etag: '"0x8D351364B2604CF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c32d3f9f-001a-0014-5e1f-835563000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata27?restype=directory')
  .reply(201, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:02 GMT',
  etag: '"0x8D351364B2604CF"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c32d3f9f-001a-0014-5e1f-835563000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata27?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:02 GMT',
  etag: '"0x8D351364B82A6EB"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1ce883b0-001a-0019-181f-83ba6f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata27?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:02 GMT',
  etag: '"0x8D351364B82A6EB"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '1ce883b0-001a-0019-181f-83ba6f000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata27?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:02 GMT',
  etag: '"0x8D351364B82A6EB"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '670df414-001a-0023-1e1f-83f9cc000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-color': 'blue,Orange,Red',
  date: 'Mon, 21 Mar 2016 03:10:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata27?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:02 GMT',
  etag: '"0x8D351364B82A6EB"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '670df414-001a-0023-1e1f-83f9cc000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-color': 'blue,Orange,Red',
  date: 'Mon, 21 Mar 2016 03:10:02 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata27?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:03 GMT',
  etag: '"0x8D351364C38B6D9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd48b6e9a-001a-0000-3b1f-839607000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .put('/directory-test-share-testdata1/dir-testdata27?restype=directory&comp=metadata')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:03 GMT',
  etag: '"0x8D351364C38B6D9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd48b6e9a-001a-0000-3b1f-839607000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata27?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:03 GMT',
  etag: '"0x8D351364C38B6D9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21d36db0-001a-002d-521f-8315c7000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-color': 'white,BLACK',
  date: 'Mon, 21 Mar 2016 03:10:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1/dir-testdata27?restype=directory')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:10:03 GMT',
  etag: '"0x8D351364C38B6D9"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '21d36db0-001a-002d-521f-8315c7000000',
  'x-ms-version': '2015-04-05',
  'x-ms-meta-color': 'white,BLACK',
  date: 'Mon, 21 Mar 2016 03:10:03 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:22 GMT',
  etag: '"0x8D3513633861736"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '536379dc-001a-000a-2d1f-838f8e000000',
  'x-ms-version': '2015-04-05',
  'x-ms-share-quota': '5120',
  date: 'Mon, 21 Mar 2016 03:10:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .head('/directory-test-share-testdata1?restype=share')
  .reply(200, "", { 'transfer-encoding': 'chunked',
  'last-modified': 'Mon, 21 Mar 2016 03:09:22 GMT',
  etag: '"0x8D3513633861736"',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '536379dc-001a-000a-2d1f-838f8e000000',
  'x-ms-version': '2015-04-05',
  'x-ms-share-quota': '5120',
  date: 'Mon, 21 Mar 2016 03:10:03 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1?restype=share')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ee03483e-001a-004a-5e1f-83a660000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:04 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.file.core.windows.net:443')
  .delete('/directory-test-share-testdata1?restype=share')
  .reply(202, "", { 'transfer-encoding': 'chunked',
  server: 'Windows-Azure-File/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'ee03483e-001a-004a-5e1f-83a660000000',
  'x-ms-version': '2015-04-05',
  date: 'Mon, 21 Mar 2016 03:10:04 GMT',
  connection: 'close' });
 return result; }]];