// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=https;AccountName=xplat;AccountKey=null';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'linearretry1\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e994c801-0002-0037-101c-833aa8000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'linearretry1\')',
  date: 'Mon, 21 Mar 2016 02:48:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'linearretry1\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e994c801-0002-0037-101c-833aa8000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'linearretry1\')',
  date: 'Mon, 21 Mar 2016 02:48:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableAlreadyExists</code><message xml:lang=\"en-US\">The table specified already exists.\nRequestId:12daa594-0002-0028-201c-83e1b8000000\nTime:2016-03-21T02:48:10.7987610Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12daa594-0002-0028-201c-83e1b8000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Mon, 21 Mar 2016 02:48:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableAlreadyExists</code><message xml:lang=\"en-US\">The table specified already exists.\nRequestId:12daa594-0002-0028-201c-83e1b8000000\nTime:2016-03-21T02:48:10.7987610Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '12daa594-0002-0028-201c-83e1b8000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Mon, 21 Mar 2016 02:48:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .get('/Tables(%27linearretry1%27)')
  .reply(200, "<?xml version=\"1.0\" encoding=\"utf-8\"?><entry xml:base=\"https://xplat.table.core.windows.net/\" xmlns=\"http://www.w3.org/2005/Atom\" xmlns:d=\"http://schemas.microsoft.com/ado/2007/08/dataservices\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\" xmlns:georss=\"http://www.georss.org/georss\" xmlns:gml=\"http://www.opengis.net/gml\"><id>https://xplat.table.core.windows.net/Tables('linearretry1')</id><category term=\"xplat.Tables\" scheme=\"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme\" /><link rel=\"edit\" title=\"Tables\" href=\"Tables('linearretry1')\" /><title /><updated>2016-03-21T02:48:11Z</updated><author><name /></author><content type=\"application/xml\"><m:properties><d:TableName>linearretry1</d:TableName></m:properties></content></entry>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/atom+xml;type=entry;charset=utf-8',
  vary: 'Origin',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9de76702-0002-0006-221c-83617f000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .get('/Tables(%27linearretry1%27)')
  .reply(200, "<?xml version=\"1.0\" encoding=\"utf-8\"?><entry xml:base=\"https://xplat.table.core.windows.net/\" xmlns=\"http://www.w3.org/2005/Atom\" xmlns:d=\"http://schemas.microsoft.com/ado/2007/08/dataservices\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\" xmlns:georss=\"http://www.georss.org/georss\" xmlns:gml=\"http://www.opengis.net/gml\"><id>https://xplat.table.core.windows.net/Tables('linearretry1')</id><category term=\"xplat.Tables\" scheme=\"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme\" /><link rel=\"edit\" title=\"Tables\" href=\"Tables('linearretry1')\" /><title /><updated>2016-03-21T02:48:11Z</updated><author><name /></author><content type=\"application/xml\"><m:properties><d:TableName>linearretry1</d:TableName></m:properties></content></entry>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/atom+xml;type=entry;charset=utf-8',
  vary: 'Origin',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '9de76702-0002-0006-221c-83617f000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry1%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4091aa8e-0002-001e-0a1c-834cea000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:11 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry1%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '4091aa8e-0002-001e-0a1c-834cea000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:11 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3557e162-0002-004b-431c-83a79d000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  date: 'Mon, 21 Mar 2016 02:48:11 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3557e162-0002-004b-431c-83a79d000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  date: 'Mon, 21 Mar 2016 02:48:11 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry2%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c354c751-0002-0014-781c-835563000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry2%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'c354c751-0002-0014-781c-835563000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableBeingDeleted</code><message xml:lang=\"en-US\">The specified table is being deleted. Try operation later.\nRequestId:e9edace0-0002-0019-211c-83ba6f000000\nTime:2016-03-21T02:48:14.2220644Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e9edace0-0002-0019-211c-83ba6f000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Mon, 21 Mar 2016 02:48:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(409, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>TableBeingDeleted</code><message xml:lang=\"en-US\">The specified table is being deleted. Try operation later.\nRequestId:e9edace0-0002-0019-211c-83ba6f000000\nTime:2016-03-21T02:48:14.2220644Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e9edace0-0002-0019-211c-83ba6f000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  date: 'Mon, 21 Mar 2016 02:48:13 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6fba1c3d-0002-003c-771c-8322dc000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  date: 'Mon, 21 Mar 2016 02:48:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/Tables', '*')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  location: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '6fba1c3d-0002-003c-771c-8322dc000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  'preference-applied': 'return-no-content',
  dataserviceid: 'https://xplat.table.core.windows.net/Tables(\'linearretry2\')',
  date: 'Mon, 21 Mar 2016 02:48:44 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .get('/Tables(%27linearretry2%27)')
  .reply(200, "<?xml version=\"1.0\" encoding=\"utf-8\"?><entry xml:base=\"https://xplat.table.core.windows.net/\" xmlns=\"http://www.w3.org/2005/Atom\" xmlns:d=\"http://schemas.microsoft.com/ado/2007/08/dataservices\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\" xmlns:georss=\"http://www.georss.org/georss\" xmlns:gml=\"http://www.opengis.net/gml\"><id>https://xplat.table.core.windows.net/Tables('linearretry2')</id><category term=\"xplat.Tables\" scheme=\"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme\" /><link rel=\"edit\" title=\"Tables\" href=\"Tables('linearretry2')\" /><title /><updated>2016-03-21T02:48:45Z</updated><author><name /></author><content type=\"application/xml\"><m:properties><d:TableName>linearretry2</d:TableName></m:properties></content></entry>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/atom+xml;type=entry;charset=utf-8',
  vary: 'Origin',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cb2e01b8-0002-0041-6e1c-83be14000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .get('/Tables(%27linearretry2%27)')
  .reply(200, "<?xml version=\"1.0\" encoding=\"utf-8\"?><entry xml:base=\"https://xplat.table.core.windows.net/\" xmlns=\"http://www.w3.org/2005/Atom\" xmlns:d=\"http://schemas.microsoft.com/ado/2007/08/dataservices\" xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\" xmlns:georss=\"http://www.georss.org/georss\" xmlns:gml=\"http://www.opengis.net/gml\"><id>https://xplat.table.core.windows.net/Tables('linearretry2')</id><category term=\"xplat.Tables\" scheme=\"http://schemas.microsoft.com/ado/2007/08/dataservices/scheme\" /><link rel=\"edit\" title=\"Tables\" href=\"Tables('linearretry2')\" /><title /><updated>2016-03-21T02:48:45Z</updated><author><name /></author><content type=\"application/xml\"><m:properties><d:TableName>linearretry2</d:TableName></m:properties></content></entry>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/atom+xml;type=entry;charset=utf-8',
  vary: 'Origin',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'cb2e01b8-0002-0041-6e1c-83be14000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry2%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '01f763b5-0002-0009-1e1c-838c89000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:45 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry2%27)')
  .reply(204, "", { 'cache-control': 'no-cache',
  'content-length': '0',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '01f763b5-0002-0009-1e1c-838c89000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:45 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:225ab2f0-0002-0022-451c-83f831000000\nTime:2016-03-21T02:48:46.6301642Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '225ab2f0-0002-0022-451c-83f831000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:225ab2f0-0002-0022-451c-83f831000000\nTime:2016-03-21T02:48:46.6301642Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '225ab2f0-0002-0022-451c-83f831000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:47f0c746-0002-0027-0b1c-830c4e000000\nTime:2016-03-21T02:48:46.1408127Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '47f0c746-0002-0027-0b1c-830c4e000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:47f0c746-0002-0027-0b1c-830c4e000000\nTime:2016-03-21T02:48:46.1408127Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '47f0c746-0002-0027-0b1c-830c4e000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:3dad3273-0002-0040-731c-83bfe9000000\nTime:2016-03-21T02:48:47.6561734Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3dad3273-0002-0040-731c-83bfe9000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:3dad3273-0002-0040-731c-83bfe9000000\nTime:2016-03-21T02:48:47.6561734Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3dad3273-0002-0040-731c-83bfe9000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:86a1c793-0002-0031-721c-83cdd0000000\nTime:2016-03-21T02:48:48.5840237Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '86a1c793-0002-0031-721c-83cdd0000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .delete('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:86a1c793-0002-0031-721c-83cdd0000000\nTime:2016-03-21T02:48:48.5840237Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '86a1c793-0002-0031-721c-83cdd0000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:47 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://xplat.table.core.windows.net:443')
  .get('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:e74bb224-0002-0036-541c-833b55000000\nTime:2016-03-21T02:48:49.1382368Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  vary: 'Origin',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e74bb224-0002-0036-541c-833b55000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://xplat.table.core.windows.net:443')
  .get('/Tables(%27linearretry3%27)')
  .reply(404, "<?xml version=\"1.0\" encoding=\"utf-8\"?><error xmlns=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><code>ResourceNotFound</code><message xml:lang=\"en-US\">The specified resource does not exist.\nRequestId:e74bb224-0002-0036-541c-833b55000000\nTime:2016-03-21T02:48:49.1382368Z</message></error>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml;charset=utf-8',
  vary: 'Origin',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'e74bb224-0002-0036-541c-833b55000000',
  'x-ms-version': '2015-04-05',
  'x-content-type-options': 'nosniff',
  date: 'Mon, 21 Mar 2016 02:48:48 GMT',
  connection: 'close' });
 return result; }]];