// This file has been autogenerated.

exports.setEnvironment = function() {
  process.env['AZURE_STORAGE_CONNECTION_STRING'] = 'DefaultEndpointsProtocol=http;AccountName=xplat;AccountKey=null';
}

exports.scopes = [[function (nock) { 
var result = 
nock('http://xplat-secondary.blob.core.windows.net:80')
  .get('/?comp=stats&restype=service')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><StorageServiceStats><GeoReplication><Status>live</Status><LastSyncTime>Wed, 05 Aug 2015 07:17:27 GMT</LastSyncTime></GeoReplication></StorageServiceStats>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'd2fdeab5-0001-0022-0f4f-cf9880000000',
  'x-ms-version': '2015-02-21',
  date: 'Wed, 05 Aug 2015 07:20:34 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat-secondary.queue.core.windows.net:80')
  .get('/?comp=stats&restype=service')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><StorageServiceStats><GeoReplication><Status>live</Status><LastSyncTime>Wed, 05 Aug 2015 07:17:23 GMT</LastSyncTime></GeoReplication></StorageServiceStats>", { 'cache-control': 'no-cache',
  'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': 'a40ede2e-0003-0014-734f-cf35d2000000',
  'x-ms-version': '2015-02-21',
  date: 'Wed, 05 Aug 2015 07:20:39 GMT',
  connection: 'close' });
 return result; }],
[function (nock) { 
var result = 
nock('http://xplat-secondary.table.core.windows.net:80')
  .get('/?comp=stats&restype=service')
  .reply(200, "﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><StorageServiceStats><GeoReplication><Status>live</Status><LastSyncTime>Wed, 05 Aug 2015 07:17:39 GMT</LastSyncTime></GeoReplication></StorageServiceStats>", { 'transfer-encoding': 'chunked',
  'content-type': 'application/xml',
  server: 'Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0',
  'x-ms-request-id': '3463ebef-0002-0018-794f-cfdb23000000',
  'x-ms-version': '2015-02-21',
  date: 'Wed, 05 Aug 2015 07:20:39 GMT',
  connection: 'close' });
 return result; }]];