language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

after_script:
  - npm run coveralls

install:
  - npm --version
  - npm install

allow_failures:
  - node_js: "5"
  - node_js: "7"

sudo: false